# Generated by Django 2.2.6 on 2019-11-25 05:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_auto_20191125_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reveiw',
            new_name='Review',
        ),
    ]
