# Generated by Django 2.2.6 on 2019-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_descript_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viedo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
