# Generated by Django 2.2.6 on 2019-11-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_viedo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='viedo',
            new_name='video',
        ),
    ]
