# Generated by Django 2.2.6 on 2019-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20191127_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.CharField(default='', max_length=300),
        ),
    ]
